# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7b468ac19684e5b95cebc5e1e3ae76f2"
name = "SyncLogic"
handle = "synclogic"
application_url = "https://vocal-fly-trackback-conduct.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bont-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_orders,read_products,write_inventory,write_products"

[auth]
redirect_urls = [
  "https://example.com/api/auth",
  "https://ranks-cadillac-enemy-harvey.trycloudflare.com/auth/callback",
  "https://ranks-cadillac-enemy-harvey.trycloudflare.com/auth/shopify/callback",
  "https://ranks-cadillac-enemy-harvey.trycloudflare.com/api/auth/callback",
  "https://dutch-generator-opposite-script.trycloudflare.com/auth/callback",
  "https://dutch-generator-opposite-script.trycloudflare.com/auth/shopify/callback",
  "https://dutch-generator-opposite-script.trycloudflare.com/api/auth/callback",
  "https://sally-timber-intl-detail.trycloudflare.com/auth/callback",
  "https://sally-timber-intl-detail.trycloudflare.com/auth/shopify/callback",
  "https://sally-timber-intl-detail.trycloudflare.com/api/auth/callback",
  "https://vocal-fly-trackback-conduct.trycloudflare.com/auth/callback",
  "https://vocal-fly-trackback-conduct.trycloudflare.com/auth/shopify/callback",
  "https://vocal-fly-trackback-conduct.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "https://sally-timber-intl-detail.trycloudflare.com/webhooks/compliance_webhooks"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://sally-timber-intl-detail.trycloudflare.com/webhooks/app_uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "inventory_levels/update" ]
  uri = "https://sally-timber-intl-detail.trycloudflare.com/webhooks/inventory_levels_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/fulfilled" ]
  uri = "https://sally-timber-intl-detail.trycloudflare.com/webhooks/orders_fulfilled"

[pos]
embedded = false
